allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.layout.buildDirectory.value(rootProject.layout.buildDirectory.dir("../../build").get())

subprojects {
    project.layout.buildDirectory.value(rootProject.layout.buildDirectory.dir(project.name).get())
}
subprojects {
    project.evaluationDependsOn(":app")
}
subprojects {
    if (project.name == "jitsi_meet_flutter_sdk") {
        project.android {
            namespace "com.example.jitsi_meet_flutter_sdk"
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
