platform :ios, '13.0'

install! 'cocoapods', :disable_input_output_paths => true

def flutter_install_all_ios_pods(chunks)
  keep_path = File.expand_path(File.join('Flutter', 'podhelper.rb'), chunks)
  require keep_path
  flutter_ios_podfile_setup
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(__FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
